### ISSUE TITLE
Feature: Bitcoin Fee Graph

### ISSUE THREAD

**Issue by Tigerix** [yanascz/bitcoin-widgets-ios#2]
How about something like this?

![image](https://github.com/yanascz/bitcoin-widgets-ios/assets/125405/3c0ff39c-f726-4791-aaa3-be7be62a413f)

**Comment by yanascz** [comment]
Not sure I understand what I'm looking at. 🙂

Is that an existing widget that shows the fees or a similar one? What does the blue number mean? What fee values would you expect to see there? Is there any public API, such as https://mempool.space/docs/api/rest, that would serve such data?

**Comment by Tigerix** [comment]
This is an iOS widget from an Ethereum Gas Fee App called GAS. 

Lets say you request the Bitcoin Medium Priority Fee every minute. Then you could build a historic graph of the Bitcoin Fees.
This way a user could see the fee history of the last x minutes. 
But thinking further about it, it might not make sense on Bitcoin, since the block time is 10 minutes.

**Comment by yanascz** [comment]
I'm not aware of a way to fetch such data from a widget every minute or so. You may hint the OS how often to refresh the widget but there's unfortunately no guarantee (to save battery life). That's why you'd need some service to do the fetching for you. I checked the mempool.space API and there doesn't seem to be a relevant endpoint available.

If you use the Mempool Status widget, there are current fees displayed. It works reasonably well if you look at the widget when you need to know the fees. Provided you're online, of course. 🙂
