### ISSUE TITLE
Trouble getting it to work on iOS 

### ISSUE THREAD

**Issue by git-501** [yanascz/bitcoin-widgets-ios#3]
Hey, I like this app but would like it much more if it would work. Trying to connect to my node but it tells me „node unreachable“ all the time. Entering the private ip of the node and 8181 as mempool port but nothing. Also the 8333 of the Bitcoin service doesn’t work. What am I doing wrong?

**Comment by yanascz** [comment]
👋 What do you mean by private IP of the node? Are you able to access the node via [Bitnodes](https://bitnodes.io/#join-the-network)?

**Comment by git-501** [comment]
Ah, sorry is this a requirement? I just want to use it with my private node with private IP. I am using VPN outside my network to access it automatically from everywhere.... 

I just tested the Bitnode accessibility and it works but only with the .onion address. I guess this doesn't work on iOS devices due to the missing TOR services there?

**Comment by yanascz** [comment]
In case you're able to connect your iPhone to the VPN and keep it connected, it might work. I tried the Orbot app in the past but it kept disconnecting and thus the widget was unhappy.

It is possible to use the .onion address in the widget configuration as well, it connects via bitnodes.io. However, it's not ideal and may not show accurate block height.

Alternatively consider setting up an SSH tunnel, see https://github.com/yanascz/bitcoind-tunnel.

**Comment by git-501** [comment]
Thanks! 

In my case I don't want my node visible in clearnet and via Tor it has its own problems, as you already mentioned...

Is this app always using bitnodes API? No way to also use it completely private? Such option would be really nice, because most people using their own nodes anyway have their solutions how to access them from outside.... :) 

Just a suggestion for more optionality 😀. In case you are not considering it, this issue can be closed as its completely the developers decision. Thanks anyways for you prompt reaction!

**Comment by yanascz** [comment]
The app uses the Bitnodes API only for .onion hosts, see https://github.com/yanascz/bitcoin-widgets-ios#configuration. It's not an ideal solution but a working compromise. I've already spent quite some time trying to get the widgets working via a Tor connection. However, due to OS constraints on widgets I couldn't get it working. 😕

The main issue with a Tor connection is that it takes a while to establish, sometimes 30 seconds or more. Even the official [Orbot app](https://support.torproject.org/glossary/orbot/) keeps disconnecting and thus is unusable for widgets. So you need a service that'll handle the Tor communication. And if you're able to set it up, you may as well set up a VPN or make your node available on a public IP with some obscure port. You don't need your node to publish that IP/port.

If you know about an easy solution that wouldn't require the node operator to install yet another service, I'm all ears. 🙂

**Comment by yanascz** [comment]
AFAIK not easily fixable at the moment.
